services:
  mongodb:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: temp_password
      MONGO_INITDB_DATABASE: mydatabase
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: