services:
  postgres:
    image: postgres:17
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: temp_password
      POSTGRES_DB: dp
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
