ktor:
  application:
    modules:
      - cz.cvut.ApplicationKt.module
  deployment:
    port: 8081
storage:
  jdbcURL: "jdbc:postgresql://db:5432/postgres"
  user: "postgres"
  password: "temp_password"


